### ISSUE TITLE
Set requests timeout

### ISSUE THREAD

**Issue by jbouzekri** [geeknam/python-gcm#121]
How can I set the request timeout when using the standard 

I had this issue on one of my process yesterday : 

```
Traceback (most recent call last):
  File "worker/0.2.1/venv/lib/python2.7/site-packages/worker/devices.py", line 134, in notify
    notifier.send_notification(self.token, message, data)
  File "worker/0.2.1/venv/lib/python2.7/site-packages/worker/devices.py", line 110, in send_notification
    self.json_request(registration_ids=[token], data=data)
  File "worker/0.2.1/venv/lib/python2.7/site-packages/gcm/gcm.py", line 317, in json_request
    response = self.make_request(payload, is_json=True)
  File "worker/0.2.1/venv/lib/python2.7/site-packages/gcm/gcm.py", line 189, in make_request
    proxies=self.proxy
  File "worker/0.2.1/venv/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "worker/0.2.1/venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "worker/0.2.1/venv/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "0.2.1/venv/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "worker/0.2.1/venv/lib/python2.7/site-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
```

How can I set the timeout value on the `requests` query ?

**Comment by alibitek** [comment]
There is a timeout parameter on the GCM class constructor: https://github.com/geeknam/python-gcm/commit/733b5979448fc01295b73e94bc9de1f20f0b68da

http://docs.python-requests.org/en/master/user/advanced/#timeouts

**Comment by jbouzekri** [comment]
My bad. I had version 0.2.0 installed. Thanks for the quick answer.

**Comment by alibitek** [comment]
timeout (float or tuple) -- (optional) How long to wait for the server to send data before giving up, as a float, or a (connect timeout, read timeout) tuple.

http://docs.python-requests.org/en/master/user/advanced/#timeouts

**Comment by jbouzekri** [comment]
Thanks, this parameter was not there on version 0.2.0 ;) I don't why the version of this package has been fixed at this value on this project I am working on. I am going to ask the creator.
